-- 01_tablas_cafeteriapostgres.sql
-- Base de gestión de clientes, tiendas, metas y satisfacción para "Café & Alma"

DROP SCHEMA IF EXISTS gestion_cafe CASCADE;
CREATE SCHEMA gestion_cafe;
SET search_path TO gestion_cafe, public;

-- =====================================================
-- 1. ZONAS
-- =====================================================
CREATE TABLE zona (
    codigo_zona VARCHAR(10) PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    responsable VARCHAR(100)
);

-- =====================================================
-- 2. TIENDAS (SUCURSALES)
-- =====================================================
CREATE TABLE tienda (
    codigo_tienda VARCHAR(10) PRIMARY KEY,
    nombre_oficial VARCHAR(100) NOT NULL,
    codigo_zona VARCHAR(10) REFERENCES zona(codigo_zona),
    ciudad VARCHAR(80),
    direccion VARCHAR(160),
    latitud NUMERIC(9,6),
    longitud NUMERIC(9,6),
    fecha_apertura DATE,
    activa BOOLEAN NOT NULL DEFAULT TRUE
);

-- =====================================================
-- 3. SEGMENTOS DE CLIENTES
-- =====================================================
CREATE TABLE segmento_cliente (
    codigo_segmento VARCHAR(10) PRIMARY KEY,
    nombre VARCHAR(60) NOT NULL,
    descripcion VARCHAR(200)
);

-- =====================================================
-- 4. CLIENTES
-- =====================================================
CREATE TABLE cliente (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento VARCHAR(25),
    nombres VARCHAR(120) NOT NULL,
    ciudad VARCHAR(80),
    fecha_nacimiento DATE,
    sexo CHAR(1),
    codigo_segmento VARCHAR(10) REFERENCES segmento_cliente(codigo_segmento),
    fecha_registro DATE,
    correo VARCHAR(120),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- =====================================================
-- 5. METAS MENSUALES
-- =====================================================
CREATE TABLE meta_mensual (
    codigo_tienda VARCHAR(10) REFERENCES tienda(codigo_tienda),
    periodo DATE NOT NULL,
    meta_ventas NUMERIC(12,2) NOT NULL,
    meta_clientes INTEGER,
    meta_satisfaccion NUMERIC(3,2),
    PRIMARY KEY (codigo_tienda, periodo)
);

-- =====================================================
-- 6. ENCUESTAS DE SATISFACCIÓN
-- =====================================================
CREATE TABLE encuesta_satisfaccion (
    id_encuesta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    codigo_tienda VARCHAR(10) REFERENCES tienda(codigo_tienda),
    documento_cliente VARCHAR(25),
    puntuacion INTEGER,
    tiempo_espera_minutos INTEGER,
    comentario VARCHAR(300)
);

-- Índices
CREATE INDEX idx_cliente_documento ON cliente(documento);
CREATE INDEX idx_encuesta_fecha ON encuesta_satisfaccion(fecha);
CREATE INDEX idx_meta_periodo ON meta_mensual(periodo);