-- 01_postgresql_cafeteria_creacion.sql
-- BASE DE GESTION - ENFOQUE EN EFICIENCIA OPERATIVA

DROP SCHEMA IF EXISTS gestion_cafe CASCADE;
CREATE SCHEMA gestion_cafe;
SET search_path TO gestion_cafe, public;

-- =====================================================
-- 1. ZONAS
-- =====================================================
CREATE TABLE zona (
    codigo_zona VARCHAR(10) PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    responsable VARCHAR(100)
);

-- =====================================================
-- 2. TIENDAS
-- =====================================================
CREATE TABLE tienda (
    codigo_tienda VARCHAR(10) PRIMARY KEY,
    nombre_oficial VARCHAR(100) NOT NULL,
    codigo_zona VARCHAR(10) REFERENCES zona(codigo_zona),
    ciudad VARCHAR(80),
    direccion VARCHAR(160),
    capacidad_maxima INT,
    maquinas_cafe INT,
    fecha_apertura DATE,
    activa BOOLEAN NOT NULL DEFAULT TRUE
);

-- =====================================================
-- 3. SEGMENTOS DE CLIENTES
-- =====================================================
CREATE TABLE segmento_cliente (
    codigo_segmento VARCHAR(10) PRIMARY KEY,
    nombre VARCHAR(60) NOT NULL,
    descripcion VARCHAR(200)
);

-- =====================================================
-- 4. CLIENTES
-- =====================================================
CREATE TABLE cliente (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento VARCHAR(25),
    nombres VARCHAR(120) NOT NULL,
    ciudad VARCHAR(80),
    fecha_nacimiento DATE,
    sexo CHAR(1),
    codigo_segmento VARCHAR(10) REFERENCES segmento_cliente(codigo_segmento),
    fecha_registro DATE,
    correo VARCHAR(120),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- =====================================================
-- 5. EMPLEADOS (Datos oficiales RRHH)
-- =====================================================
CREATE TABLE empleado_gestion (
    id_empleado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento VARCHAR(20),
    nombres VARCHAR(120),
    cargo VARCHAR(50),
    salario_mensual DECIMAL(10,2),
    fecha_contratacion DATE,
    codigo_tienda VARCHAR(10) REFERENCES tienda(codigo_tienda),
    certificacion VARCHAR(50),
    activo BOOLEAN DEFAULT TRUE
);

-- =====================================================
-- 6. HORARIO IDEAL (Planificación de turnos)
-- =====================================================
CREATE TABLE horario_ideal (
    id_horario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_tienda VARCHAR(10) REFERENCES tienda(codigo_tienda),
    dia_semana VARCHAR(10),
    hora_inicio TIME,
    hora_fin TIME,
    baristas_requeridos INT,
    UNIQUE (codigo_tienda, dia_semana, hora_inicio, hora_fin)  -- ✅ Agregado
);

-- =====================================================
-- 7. META OPERATIVA
-- =====================================================
CREATE TABLE meta_operativa (
    id_meta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_tienda VARCHAR(10) REFERENCES tienda(codigo_tienda),
    periodo DATE,
    meta_tiempo_espera_seg INT,
    meta_productividad_min DECIMAL(5,2),
    meta_merma_max DECIMAL(5,2),
    UNIQUE (codigo_tienda, periodo)  -- ✅ Agregado
);

-- =====================================================
-- 8. ENCUESTA CALIDAD
-- =====================================================
CREATE TABLE encuesta_calidad (
    id_encuesta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    codigo_tienda VARCHAR(10) REFERENCES tienda(codigo_tienda),
    documento_cliente VARCHAR(25),
    puntuacion_calidad_cafe INTEGER,
    puntuacion_rapidez INTEGER,
    puntuacion_amabilidad INTEGER,
    comentario VARCHAR(300)
);

-- INDICES
CREATE INDEX idx_empleado_tienda ON empleado_gestion(codigo_tienda);
CREATE INDEX idx_horario_tienda ON horario_ideal(codigo_tienda);
CREATE INDEX idx_meta_periodo ON meta_operativa(periodo);
CREATE INDEX idx_encuesta_fecha ON encuesta_calidad(fecha);