services:
  mysql:
    image: mysql:8.4
    container_name: bi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cafeteria_db
      MYSQL_USER: gerson
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ../../data/mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro

  postgres:
    image: postgres:16
    container_name: bi_postgres
    environment:
      POSTGRES_DB: cafeteria_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5444:5432"
    volumes:
      - ../../data/postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
  
  staging:
    image: postgres:16
    container_name: staging
    environment:
        POSTGRES_DB: datawarehouse
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
    ports:
      - "5450:5432"
    volumes:
      - ../../data/datawarehouse_data:/var/lib/postgresql/data
      - ./datawarehouse-init:/docker-entrypoint-initdb.d:ro
  
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports: 
      - "8090:8080"
    depends_on:
      - mysql
      - postgres
      - staging